# .streamlit/config.toml

[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = false

[client]
toolbarMode = "viewer"

[browser]
gatherUsageStats = false

[global]
minCachedMessageSize = 2
maxCachedMessageSize = 200

[runner]
magicEnabled = true
fastReruns = true

[logger]
level = "info"
